openapi: 3.0.3
info: 
  title: Swagger
  description: Docs
servers:
  - url: http://localhost:3000
tags:
  - name: sample
    description: sample tag
paths:
    /test:
      get:
        tags:
          - "sample"
        summary: sample get
        responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  type: string
                  example: "Hello"
          '400':
            description: Invalid ID supplied