@startuml
actor Admin
participant "Admin Interface" as AdminUI
participant "Controller" as Controller
database "Database" as DB

Admin -> AdminUI: Select cateogry to update
AdminUI -> Controller: Send updated cateogry information
Controller -> DB: Retrieve cateogry information
DB --> Controller: Cateogry information
Controller -> DB: Update cateogry information
DB --> Controller: Update confirmation
Controller --> AdminUI: Cateogry update success message
AdminUI --> Admin: Cateogry update confirmation
@enduml